{%@@if "dev" in profile @@%}
export http_proxy=http://tst-proxy.genua.de:8888
export https_proxy=http://tst-proxy.genua.de:8888
{%@@ endif @@%}

alias dotdrop=~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml


touch ~/.bashrc_local
source ~/.bashrc_local
