call plug#begin('~/.vim/plugged')
" Autopairs
Plug 'tmsvg/pear-tree'

" Git diff in gutter
Plug 'airblade/vim-gitgutter'

" Colorscheme
Plug 'morhetz/gruvbox'

" Tagbar
Plug 'majutsushi/tagbar'

" Show indentation
Plug 'Yggdroot/indentLine'

" Fugitive
Plug 'tpope/vim-fugitive'
call plug#end()
" General settings
source ~/.vim/local-settings.vim
behave xterm
syntax enable

set autoindent
set smarttab
set textwidth=120
set expandtab
set nowrap
set showfulltag
set undolevels=1000
set history=200
set showmatch
set noswapfile
set backspace=indent,eol,start
set noautowrite
set nobackup
set spelllang=en_us,de_de
set ruler
set relativenumber
set number
set laststatus=2
filetype on
filetype plugin on
filetype indent plugin on

" disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>


" gruvbox
colorscheme gruvbox
set background=dark

" transparency
hi Normal guibg=NONE ctermbg=NONE

" line limit column
set colorcolumn=80

" highlight current line
set cursorline

" show whitespaces / tabs
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
" Change cursor shape in different modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Netrw config
let g:netrw_banner = 0
let g:netrw_browse_split = 2

autocmd StdinReadPre * let s:std_in=1
" automatically open netrw when no file is specified
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif
" automatically open netrw when opening a directory
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif

" open netrw on Ctrl + N
map <C-n> :Vex<CR>

" Tagbar
map <C-t> :TagbarToggle<CR>

" git gutter
autocmd BufWritePost * GitGutter

" Pear tree
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1
