let mapleader = "\<Space>"
" General settings
syntax enable
set nocompatible
set autoindent
set smarttab
set textwidth=100
set expandtab
set nowrap
set showfulltag
set undolevels=1000
set history=200
set showmatch
set noswapfile
set backspace=indent,eol,start
set noautowrite
set nobackup
set ruler
set relativenumber
set number
set laststatus=2
set ignorecase
set whichwrap=b,s,h,l,<,>,[,]
set hlsearch
set foldmethod=indent
set foldlevel=99
set autoread
set smartindent

set encoding=utf-8
set fileencodings=ucs-bom,ascii,utf-8,latin1

filetype on
filetype plugin on
filetype indent plugin on

" Set 256 colors for my terminal
set t_Co=256

" transparency
hi Normal guibg=NONE ctermbg=NONE

" line limit column
set colorcolumn=100

" highlight current line
set cursorline

" show whitespaces / tabs
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+\%#\@<!$/

" Change cursor shape in different modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Netrw config
let g:netrw_banner = 0
let g:netrw_browse_split = 0

autocmd StdinReadPre * let s:std_in=1
" automatically open netrw when no file is specified
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif
" automatically open netrw when opening a directory
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif

" Make the cursor follow the split
set splitbelow
set splitright

" enable nvim plugins
if has("nvim")
  lua require'hboeving.init'
endif
