let mapleader = "\<Space>"
call plug#begin('~/.vim/plugged')
" Colorscheme
Plug 'morhetz/gruvbox'

" Automatically switch indent config
Plug 'tpope/vim-sleuth'

" Giiiiit
Plug 'airblade/vim-gitgutter'

" Tmux navigation!
Plug 'christoomey/vim-tmux-navigator'

" Automatically add end in ruby
Plug 'tpope/vim-endwise'

" Automatically add and delete pairs
Plug 'jiangmiao/auto-pairs'

" Fzf
if executable("fzf")
    Plug 'junegunn/fzf'
    Plug 'junegunn/fzf.vim'
endif

if has("nvim") && has("nvim-0.5.0")
  Plug 'nvim-lua/completion-nvim'
  Plug 'steelsojka/completion-buffers'
  Plug 'Shougo/neosnippet.vim'
  Plug 'Shougo/neosnippet-snippets'

  if (executable("clang") || executable("gcc")) && executable("git")
    Plug 'nvim-treesitter/nvim-treesitter'
    Plug 'nvim-treesitter/completion-treesitter'
  endif
  Plug 'neovim/nvim-lspconfig'
endif

call plug#end()

" General settings
behave xterm
syntax enable
set nocompatible
set autoindent
set smarttab
set textwidth=120
set expandtab
set nowrap
set showfulltag
set undolevels=1000
set history=200
set showmatch
set noswapfile
set backspace=indent,eol,start
set noautowrite
set nobackup
set ruler
set relativenumber
set number
set laststatus=2
set ignorecase
set whichwrap=b,s,h,l,<,>,[,]
set hlsearch
set foldmethod=indent
set foldlevel=99
set autoread
set smartindent

set encoding=utf-8
set termencoding=utf-8
set fileencodings=ucs-bom,ascii,utf-8,latin1

filetype on
filetype plugin on
filetype indent plugin on

" colorscheme
colorscheme gruvbox
set background=dark
if has("nvim")
  set termguicolors
endif

" Set 256 colors for my terminal
set t_Co=256

" transparency
hi Normal guibg=NONE ctermbg=NONE

" line limit column
set colorcolumn=80

" highlight current line
set cursorline

" show whitespaces / tabs
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+\%#\@<!$/

" Change cursor shape in different modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Netrw config
let g:netrw_banner = 0
let g:netrw_browse_split = 0

autocmd StdinReadPre * let s:std_in=1
" automatically open netrw when no file is specified
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif
" automatically open netrw when opening a directory
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | Ex | endif

" Make the cursor follow the split
set splitbelow
set splitright

" Git mappings
autocmd BufWritePost * GitGutter

" Fzf files
nmap <leader>ff :Files<CR>
" Fzf Tab Files
nmap <leader>ft :tabe<CR>:Files<CR>
" Fzf Ctags
nmap <leader>fc :BTags<CR>

" enable nvim plugins
if has("nvim") && has("nvim-0.5.0")
  lua require'hboeving.completion'

  if (executable("clang") || executable("gcc")) && executable("git")
    lua require'hboeving.treesitter'
  endif

  lua require'hboeving.lsp'
endif
