export ZSH="/home/$USER/.oh-my-zsh"
ZSH_THEME="hbv-pygmalion"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  common-aliases
  compleat
  history
  vi-mode
)

source $ZSH/oh-my-zsh.sh
export EDITOR="vim"
alias zshconfig="vim ~/.zshrc"
alias dotdrop=~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml
export PATH=$HOME/.ls/lsp_init:$HOME/.local/bin:$PATH
export KEYTIMEOUT=1 # for vi mode switch

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# common-aliases changes this to grep --color, this doesnt work under obsd
alias grep=grep

if [ -f ~/.ssh/agent.env ] ; then
    . ~/.ssh/agent.env > /dev/null
    if ! kill -0 $SSH_AGENT_PID > /dev/null 2>&1; then
        echo "Stale agent file found. Spawning a new agent. "
        eval `ssh-agent | tee ~/.ssh/agent.env`
        ssh-add
    fi
else
    echo "Starting ssh-agent"
    eval `ssh-agent | tee ~/.ssh/agent.env`
    ssh-add
fi

touch ~/.github_token
source ~/.github_token

touch ~/.zshrc_local
source ~/.zshrc_local
