export ZSH="/home/$USER/.oh-my-zsh"
ZSH_THEME="hbv-pygmalion"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
  git
  common-aliases
  compleat
  history
  ssh-agent
  vi-mode
)

# common-aliases changes this to grep --color, this doesnt work under obsd
alias grep=grep

{%@@ if profile == "workstation" @@%}
zstyle :omz:plugins:ssh-agent identities id_rsa openstack gitlab github
{%@@ elif profile == "laptop" @@%}
zstyle :omz:plugins:ssh-agent indentities id_rsa
{%@@ endif @@%}

source $ZSH/oh-my-zsh.sh
export EDITOR="vim"
alias zshconfig="vim ~/.zshrc"
alias dotdrop=~/dotfiles/dotdrop.sh --cfg=~/dotfiles/config.yaml
export PATH=$HOME/.ls/lsp_init:$HOME/.local/bin:$PATH
export KEYTIMEOUT=1 # for vi mode switch

{%@@if "dev" in profile @@%}
export http_proxy=http://tst-proxy.genua.de:8888
export https_proxy=http://tst-proxy.genua.de:8888
alias grep=grep
{%@@ endif @@%}

touch ~/.github_token
source ~/.github_token

touch ~/.zshrc_local
source ~/.zshrc_local
